server:
  port: 8080
spring:
  application:
    name: financial-control
  datasource:
    url: jdbc:h2:mem:finances
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect